### ISSUE TITLE
[Recognition] LBP based head Recognition

### ISSUE THREAD

**Issue by 22ema** [22ema/ComputerVision#1]
## Feature
implement LBP based head Recognition code. 

## Description
LBP hisogram을 만들기 위해서 그림2와 같은 연산이 필요하다. 알고리즘은 아래와 같다.
1. 3x3 block으로 이미지의 pixel정보를 얻어온다.
2. center pixel을 중심으로 나머지 픽셀들과 크기비교를 한다. center pixel 보다 크거나 같다면 1 작다면 0으로 계산한다.
3. 좌측 pixel 부터 차례대로 나열하여 11001011이라는 2진수를 만든다. 그리고 이를 다시 10진수로 바꾸면 203이라는 값이나오고 이 값이 중간 픽셀의 값으로 바뀌게된다.

To make the LBP hisogram, the operation shown in Figure 2 is required. The algorithm is as follows.
1. Get image pixel information in 3x3 block.
2. Compare the size with the rest of the pixels centering on the center pixel. It is calculated as 1 if it is greater than or equal to the center pixel and 0 if it is less than the center pixel.
3. Make a binary number 11001011 by arranging the pixels in order from the left. And if you convert it back to a decimal number, you get a value of 203, and this value is changed to the value of the middle pixel.
## ToDo
- [x] image cropping code
- [x] implement LBP algrithm
- [x] implemnet running code
